# trigger the pipeline on a push on the main branch
trigger:
- no_main

pool:
  vmImage: ubuntu-latest          # use an ubuntu image with java 17 installed

# set variables. Get the volatile one from the library group. The rest is set to point to directories for easy reading
variables:
  - group: customer-app-vars
  - name: CORE_DIR
    value: $(Pipeline.Workspace)/core
  - name: EXTERNAL_DIR
    value: $(Pipeline.Workspace)/SW-external

# ### Directory structure
# $(Pipeline.Workspace)/repo     contains the repository and become the working directory
# $(Pipeline.Workspace)/core     contains the core installation of Smallworld
# Build.ArtifactStagingDirectory contains the zipfiles to be uploaded as artifacts
# 
jobs:
- job: Download
  steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 2 
      workspaceRepo: true
      path: repo

    # note this script runs in /repo
    - script: |
        pwd
        ls
        git diff --name-only HEAD HEAD~1 > $(Pipeline.Workspace)/changed_files.txt
      displayName: 'Get changed files'

    ################
    ## TEMPORARY CODE TO SIMULATE DETECTION OF CHANGED FILES
    ## TO BE REMOVED WHEN THE DETECTION SCRIPT IS FUNCTIONAL
    ################
    - script: |
        echo '##vso[task.setvariable variable=products_config;isOutput=true]{"customer_engine_app": {"product_path": "/home/vsts/work/1/repo/customer_engine_app", "product_name": "customer_engine_app", "product_type": "layered_product"}}'
      name: detect_products
    - script: |
        echo '$(detect_products.products_config)' > products_config.json
      name: print_products
      displayName: "create a JSON file with products config"
      workingDirectory: $(Pipeline.Workspace)


    - task: JavaToolInstaller@1
      displayName: 'Activate java 17 sdk'
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: UniversalPackages@0
      displayName: 'Download the core application'
      inputs:
        command: download
        vstsFeed: '$(AZ_FEED)'
        vstsFeedPackage: 'cst.jar'
        vstsPackageVersion: $(SW_VERSION)
        downloadDirectory: '$(CORE_DIR)'

    - task: UniversalPackages@0
      displayName: 'Download munit'
      inputs:
        command: download
        vstsFeed: '$(AZ_FEED)'
        vstsFeedPackage: 'munit.zip'
        vstsPackageVersion: $(SW_VERSION)
        downloadDirectory: '$(EXTERNAL_DIR)'
    - script: |
        cd $(EXTERNAL_DIR)
        pwd
        ls -la
      displayName: 'Debug list the situation'
    - task: ExtractFiles@1
      displayName: 'Extract munit.zip'
      inputs:
        archiveFilePatterns: '$(EXTERNAL_DIR)/munit.zip'
        destinationFolder: '$(EXTERNAL_DIR)'
        cleanDestinationFolder: false

    - script: |
        cd $(EXTERNAL_DIR)
        pwd
        ls -la
      displayName: 'Debug list the situation'

    - script: |
        sudo java -Daccept_licences="YES" -Dinstall_language_packs="YES" -jar $(CORE_DIR)/core_installer.jar $(CORE_DIR) vsts vsts
      displayName: 'Install the core products'
      workingDirectory: $(Pipeline.Workspace)

    - script: |
        $(CORE_DIR)/core/bin/share/runalias -j -Djava.awt.headless=true base -products_config $(Pipeline.Workspace)/products_config.json -test_output_dir $(Common.TestResultsDirectory) -test_aspects $(MUNIT_TEST_ASPECTS) > test_run.log
      displayName: 'Run the script /run_tests.magik to run the munit tests of the given aspects'
      workingDirectory: '$(Pipeline.Workspace)'
      timeoutInMinutes: 2
      env:
        SW_MSF_STARTUP_MAGIK: '$(Build.SourcesDirectory)/scripts/run_tests.magik'
        CUSTOMER_APP_BASE_DIR: '$(Build.SourcesDirectory)'
        SMALLWORLD_REGISTRY: '$(Build.SourcesDirectory)/smallworld_registry'

    - script: |
        cat test_run.log
      condition: always()
      workingDirectory: '$(Pipeline.Workspace)'
      displayName: 'Display test run log'
    
    - task: PublishTestResults@2
      displayName: 'Publish MUnit test results'
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '$(Pipeline.Workspace)/test_result_30.txt'
        failTaskOnFailedTests: true