variables:
  - name: AZ_SW_PRODUCT_TO_BUILD
    value: customer_app
  - name: CUSTOMER_APP_VERSION
    value: '17'
  - name: CUSTOMER_ARTIFACT
    value: $(AZ_SW_PRODUCT_TO_BUILD)-$(CUSTOMER_APP_VERSION).zip
  - name: REGISTRY_ARTIFACT
    value: smallworld_registry-$(CUSTOMER_APP_VERSION).zip
  - name: DEPLOY_DIR
    value: 'C:\SW-App'
  - name: RUN_ARTIFACT
    value: run-$(CUSTOMER_APP_VERSION).zip

jobs:
- deployment: Deploy_VM_with_Customer_App
  displayName: Customer App on VMFrank
  pool:
    vmImage: 'Ubuntu-latest'
  environment: 
    name: 'Customer_App_Dev.VMFrank'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: |
            echo | whoami
            dir
        # upload customer app
        - task: UniversalPackages@0
          displayName: Download customer app artifact
          inputs:
            command: download
            vstsFeed: 'SW/froggie'
            vstsFeedPackage: $(CUSTOMER_ARTIFACT)
            vstsPackageVersion: '*'
            downloadDirectory: '$(System.DefaultWorkingDirectory)'
        - task: UniversalPackages@0
          displayName: Download smallworld_registry
          inputs:
            command: download
            vstsFeed: 'SW/froggie'
            vstsFeedPackage: $(REGISTRY_ARTIFACT)
            vstsPackageVersion: '*'
            downloadDirectory: '$(System.DefaultWorkingDirectory)'
        - task: UniversalPackages@0
          displayName: Download run folder
          inputs:
            command: download
            vstsFeed: 'SW/froggie'
            vstsFeedPackage: $(RUN_ARTIFACT)
            vstsPackageVersion: '*'
            downloadDirectory: '$(System.DefaultWorkingDirectory)'
            
        - task: ExtractFiles@1
          displayName: Extract custom app artifact
          inputs:
            archiveFilePatterns: '*.zip'
            destinationFolder: $(DEPLOY_DIR)

