# trigger the pipeline on a push on the main branch
trigger:
- no_main

pool:
  vmImage: ubuntu-latest          # use an ubuntu image with java 17 installed

# set variables. Get the volatile one from the library group. The rest is set to point to directories for easy reading
variables:
  - group: customer-app-vars
  - name: CORE_DIR
    value: $(Pipeline.Workspace)/core
  - name: EXTERNAL_DIR
    value: $(Pipeline.Workspace)/SW-external

# ### Directory structure
# $(Build.SourcesDirectory)           contains the repository and become the working directory
# $(Pipeline.Workspace)/core          contains the core installation of Smallworld
# Build.ArtifactStagingDirectory      contains the zipfiles to be uploaded as artifacts
# $(Common.TestResultsDirectory)      contains the test results to be published
# 
jobs:
- job: Download
  steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 2 
    - script: |
        ls -al $(Build.SourcesDirectory)
        ls -al $(Pipeline.Workspace)
      displayName: 'List files in source and workspace directories'

    - task: ArchiveFiles@2
      displayName: 'Archive the compiled product'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        archiveType: 'zip'
        archiveFile: '$(Pipeline.Workspace)/repo.zip'
    - script: |
        ls -al $(Build.SourcesDirectory)
        ls -al $(Pipeline.Workspace)
      displayName: 'List files in source and workspace directories'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish compiled result (repo.zip) to be reused in the Archive job'
      inputs:
        targetPath: '$(Pipeline.Workspace)/repo.zip'
        artifact: 'repo_zip'
        publishLocation: 'pipeline'
- job: Recall
  dependsOn: Download
  steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      displayName: 'Download compiled result (repo.zip) from the Download job'
      inputs:
        artifact: 'repo_zip'
        targetPath: '$(Pipeline.Workspace)'        
    - script: |
        ls -al $(Build.SourcesDirectory)
        ls -al $(Pipeline.Workspace)
      displayName: 'List files in source and workspace directories'
    - task: ExtractFiles@1
      displayName: 'Extract repo.zip'
      inputs:
        archiveFilePatterns: '$(Pipeline.Workspace)/repo.zip'
        destinationFolder: '$(Pipeline.Workspace)'
        cleanDestinationFolder: false
    - script: |
        ls -al $(Build.SourcesDirectory)
        ls -al $(Pipeline.Workspace)
      displayName: 'List files in source and workspace directories'
