# trigger the pipeline on a push on the main branch
trigger:
- no_main

pool:
  vmImage: ubuntu-latest          # use an ubuntu image with java 17 installed

# set variables. Get the volatile one from the library group. The rest is set to point to directories for easy reading
variables:
  - group: customer-app-vars
  - name: CORE_DIR
    value: $(Pipeline.Workspace)/core

# ### Directory structure
# $(Pipeline.Workspace)/repo     contains the repository and become the working directory
# $(Pipeline.Workspace)/core     contains the core installation of Smallworld
# Build.ArtifactStagingDirectory contains the zipfiles to be uploaded as artifacts
# 
jobs:
- job: Download
  steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 2 
      workspaceRepo: false
      path: repo

      # note this script runs in /repo
    - script: |
        git diff --name-only HEAD HEAD~1 > ..\changed_files.txt
        cat ..\changed_files.txt
        cat $(Pipeline.Workspace)/changed_files.txt
      displayName: 'Get changed files'

    - task: PythonScript@0
      displayName: 'Detect products'
      name: detect_products
      inputs:
        scriptSource: 'filePath'
        scriptPath: 'scripts/detect_products.py'
        arguments: '. 2 $(Pipeline.Workspace)/changed_files.txt products_config'
        failOnStderr: true
- job: Compile
  variables:
    anything_changed: $[ ne(dependencies.Download.outputs['detect_products.products_config'], '{}') ]
  condition: eq(variables.anything_changed, true)
  dependsOn: Download
  steps:
    - script: echo "Changes detected, proceeding to compile."
      displayName: 'Confirm changes detected'