# trigger the pipeline on a push on the main branch
trigger:
- no_main

pool:
  vmImage: ubuntu-latest          # use an ubuntu image with java 17 installed

variables:
  - name: product_names
    value: ''
steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 2 
    workspaceRepo: true
    path: repo
  - script: |
      pwd
      ls
      git diff --name-only HEAD HEAD~1 > changed_files.txt
  - task: PythonScript@0
    name: detect_products
    inputs:
      scriptSource: 'filePath' # 'filePath' | 'inline'. Required. Script source. Default: filePath.
      scriptPath: scripts/detect_products.py # string. Required when scriptSource = filePath. Script path. 
      #script: # string. Required when scriptSource = inline. Script. 
      arguments: ". 2 name var1"
      # Advanced
      #pythonInterpreter: # string. Python interpreter. 
      #workingDirectory: # string. Working directory. 
      failOnStderr: true
    displayName: 'Test Script'
  - script: |
      echo "Detected products: $(var1)"
      echo "##vso[task.setvariable variable=var1;]['1','2']"
  - template: single-deploy.yml
    parameters:
      products:  $(var1)
