# trigger the pipeline on a push on the main branch
trigger:
- no_main

pool:
  vmImage: ubuntu-latest          # use an ubuntu image with java 17 installed

steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 2 
    workspaceRepo: true
    path: repo
  - script: |
      pwd
      ls
      cd repo
      git diff --name-only HEAD HEAD~1 > .\..\changed_files.txt
      cd ..
      ls
      cat changed_files.txt
    displayName: 'Test Script'