# trigger the pipeline on a push on the main branch
trigger:
- no_main

pool:
  vmImage: ubuntu-latest          # use an ubuntu image with java 17 installed

steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 2 
    workspaceRepo: true
    path: repo
  - script: |
      pwd
      ls
      git diff --name-only HEAD HEAD~1 > changed_files.txt
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath' # 'filePath' | 'inline'. Required. Script source. Default: filePath.
      scriptPath: scripts/detect_products.py # string. Required when scriptSource = filePath. Script path. 
      #script: # string. Required when scriptSource = inline. Script. 
      arguments: ". 2 name var1"
      # Advanced
      #pythonInterpreter: # string. Python interpreter. 
      #workingDirectory: # string. Working directory. 
      failOnStderr: true
    displayName: 'Test Script'
  - ${{ each product_name in variables.var1 }}:
    - script: |
        echo $(product_name)