# trigger the pipeline on a push on the main branch
trigger:
- no_main

pool:
  vmImage: ubuntu-latest          # use an ubuntu image with java 17 installed

# set variables. Get the volatile one from the library group. The rest is set to point to directories for easy reading
variables:
  - group: customer-app-vars
  - name: CORE_DIR
    value: $(Pipeline.Workspace)/core
  - name: EXTERNAL_DIR
    value: $(Pipeline.Workspace)/SW-external

# ### Directory structure
# $(Build.SourcesDirectory)           contains the repository and become the working directory
# $(Pipeline.Workspace)/core          contains the core installation of Smallworld
# Build.ArtifactStagingDirectory      contains the zipfiles to be uploaded as artifacts
# $(Common.TestResultsDirectory)      contains the test results to be published
# 
jobs:
- job: Download
  steps:
    - checkout: none

    ################
    ## TEMPORARY CODE TO SIMULATE DETECTION OF CHANGED FILES
    ## TO BE REMOVED WHEN THE DETECTION SCRIPT IS FUNCTIONAL
    ################
    - script: |
        echo '##vso[task.setvariable variable=products_config;isOutput=true]{"customer_engine_app": {"product_path": "$(Build.SourcesDirectory)/customer_engine_app", "product_name": "customer_engine_app", "product_type": "layered_product"}}'
      name: detect_products


- job: Compile
  variables:
    products_config: $[ dependencies.Download.outputs['detect_products.products_config'] ]
    anything_changed: $[ ne(variables.products_config, '{}') ]
    need_compile: $[ contains(variables.products_config, 'layered_product') ]
  condition: eq(variables.anything_changed, 'true')
  dependsOn: Download
  steps:
    - checkout: none

    - script: |
        echo "$(need_compile)"
        echo "$(anything_changed)"
      displayName: 'Check if compile is needed'

    - script: |
        echo "doing it"
      condition: eq(variables.need_compile, true)
    - script: |
        echo "after doing it"

    - ${{ if eq(variables.need_compile, true) }}:
      - script: |
          echo "doing it"
    - script: |
        echo "after doing it"

    - ${{ if eq(variables['need_compile'], true) }}:
      - script: |
          echo "doing it 2"
    - script: |
        echo "after doing it 2"
    - ${{ if eq(variables.need_compile, 'True') }}:
      - script: |
          echo "doing it"
    - script: |
        echo "after doing it"

    - ${{ if eq(variables['need_compile'], 'True') }}:
      - script: |
          echo "doing it 2"
    - script: |
        echo "after doing it 2"

    - ${{ if eq(variables.need_compile, 'true') }}:
      - script: |
          echo "doing it"
    - script: |
        echo "after doing it"

    - ${{ if eq(variables['need_compile'], 'true') }}:
      - script: |
          echo "doing it 2"
    - script: |
        echo "after doing it 2"