parameters:
  - name: AZ_FULL_DEPLOY
    type: boolean
    default: false

# set variables. Get the volatile one from the library group. The rest is set to point to directories for easy reading
variables:
  - group: customer-app-vars
  - name: REPO_NAME
    value: ${{split(variables['Build.Repository.Name'], '/')[-1]}}
  - name: APP_DEPLOY_DIR
    value: '$(REPO_NAME)-$(Build.BuildId)'
  - name: REAL_DEPLOY_DIR
    value: '$(DEPLOY_DIR)\$(APP_DEPLOY_DIR)'
  #AZ_FEED
  #DEPLOY_DIR
  #SW_VERSION
  #CUSTOMER_APP_VERSION

# pool:
#   vmImage: 'Ubuntu-latest'

jobs:
- deployment: Deploy_VM_with_customer_app
  displayName: 'Deploy Customer App on VMFrank'
  environment: 
    name: 'Customer_App_dev.VMFrank'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          displayName: Checkout just the artifacts
          sparseCheckoutPatterns: artifacts.json base-artifacts.json scripts/*
          fetchDepth: 0

        - script: |
            echo SET CUSTOMER_PRD_BASE_DIR="$(REAL_DEPLOY_DIR)" > "$(DEPLOY_DIR)\set_base_dir.bat"
          displayName: 'Redirect the application to the new checkout'

        - task: PythonScript@0
          displayName: 'Download and install artifacts'
          name: download_and_install_artifacts
          inputs:
            scriptSource: 'filePath'
            scriptPath: 'scripts\deploy.py'
            arguments: '$(Build.SourcesDirectory)\artifacts.json $(CUSTOMER_APP_VERSION) $(DEPLOY_DIR) $(APP_DEPLOY_DIR) $(Build.SourcesDirectory)\base-artifacts.json $(AZ_FULL_DEPLOY)'
            failOnStderr: true
