parameters:
  - name: AZ_BUILD_ALL
    type: boolean
    default: false
  - name: AZ_BUILD_THIS
    type: string
    default: '{}'
  - name: AZ_DEBUG
    type: boolean
    default: false

#### Directory structure
# $(Build.SourcesDirectory)           contains the repository and become the working directory
# $(Pipeline.Workspace)/***           contains the core installation of Smallworld and other base artifacts
# $(Build.ArtifactStagingDirectory)   contains the zipfiles to be uploaded as artifacts
# $(Common.TestResultsDirectory)      contains the test results to be published
# 
# set variables. Get the volatile one from the library group.
variables:
  - group: customer-app-vars
  - name: CORE_DIR
    value: $(Pipeline.Workspace)/$(SW_CORE_DIR)

# trigger the pipeline on a push on the main branch
trigger:
- no_main

pool:
  vmImage: ubuntu-latest          # use an ubuntu image with java 17 installed

steps:
- checkout: self
  displayName: 'Checkout the repository'
  persistCredentials: true
  fetchDepth: 2

- ${{ if eq(parameters.AZ_BUILD_ALL, true) }}:
  - script: |
      cp ./artifacts.json $(Pipeline.Workspace)/products_config.json
    displayName: 'Build all products - copy artifacts.json to products_config.json'
- ${{ elseif ne(parameters.AZ_BUILD_THIS, '{}') }}:
  - script: |
      echo '${{parameters.AZ_BUILD_THIS}}' > $(Pipeline.Workspace)/products_config.json
    displayName: 'Build this product - set products_config.json to AZ_BUILD_THIS variable'
- ${{ else }}:
  - script: |
      git diff --name-only HEAD HEAD~1 > $(Pipeline.Workspace)/changed_files.txt
    displayName: 'Get changed files and store them in changed_files.txt'

  - task: PublishPipelineArtifact@1
    condition: eq(${{parameters.AZ_DEBUG}}, true)
    displayName: 'Publish changed_files.txt for debugging purposes'
    inputs:
      targetPath: '$(Pipeline.Workspace)/changed_files.txt'
      artifact: 'changed_files'
      publishLocation: 'pipeline'

  - task: PythonScript@0
    displayName: 'Detect products'
    name: detect_changes
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'scripts/detect_products.py'
      arguments: '$(Pipeline.Workspace)/changed_files.txt ./artifacts.json $(Pipeline.Workspace)/products_config.json'
      failOnStderr: true
# ${{ endif }}

- task: PublishPipelineArtifact@1
  displayName: 'Publish products_config.json for debugging purposes'
  condition: eq(${{parameters.AZ_DEBUG}}, true)
  inputs:
    targetPath: '$(Pipeline.Workspace)/products_config.json'
    artifact: 'products_config'
    publishLocation: 'pipeline'

- task: JavaToolInstaller@1
  displayName: 'Activate java 17 sdk'
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: PythonScript@0
  displayName: 'Download and install core and base artifacts'
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'scripts/install.py'
    arguments: '"$(Pipeline.Workspace)" "$(System.CollectionUri)" "$(System.TeamProject)" "$(AZ_FEED)" "$(Build.SourcesDirectory)/base_artifacts.json" "$(Pipeline.Workspace)/products_config.json"'
    failOnStderr: false # because somehow something is written to Stderr even when nothing is failing....
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

- script: |
    $(CORE_DIR)/core/bin/share/runalias -j -Djava.awt.headless=true swaf -products_config $(Pipeline.Workspace)/products_config.json > compile.log
  displayName: 'Run the script $SW_MSF_STARTUP_MAGIK to compile and build'
  workingDirectory: '$(Pipeline.Workspace)'
  env:
    SW_MSF_STARTUP_MAGIK: '$(Build.SourcesDirectory)/scripts/compile_and_build.magik'
    CUSTOMER_PRD_BASE_DIR: '$(Build.SourcesDirectory)'
    SMALLWORLD_REGISTRY: '$(Build.SourcesDirectory)/smallworld_registry'

- task: PublishPipelineArtifact@1
  condition: and(succeededOrFailed(), eq(${{parameters.AZ_DEBUG}}, true))
  displayName: 'Publish compile log for debugging purposes'
  inputs:
    targetPath: '$(Pipeline.Workspace)/compile.log'
    artifact: 'compile_log'
    publishLocation: 'pipeline'

- task: UniversalPackages@0
  displayName: 'Download jacoco'
  inputs:
    command: download
    vstsFeed: '$(System.TeamProject)/$(AZ_FEED)'
    vstsFeedPackage: 'jacoco.zip'
    vstsPackageVersion: $(JACOCO_VERSION)
    downloadDirectory: '$(Pipeline.Workspace)'

- task: ExtractFiles@1
  displayName: 'Extract jacoco.zip'
  inputs:
    archiveFilePatterns: '$(Pipeline.Workspace)/jacoco.zip'
    destinationFolder: '$(Pipeline.Workspace)/jacoco'
    cleanDestinationFolder: false

- task: UniversalPackages@0
  displayName: 'Download jacoco reporter'
  inputs:
    command: download
    vstsFeed: '$(System.TeamProject)/$(AZ_FEED)'
    vstsFeedPackage: 'sw5-jacoco-reporter.jar'
    vstsPackageVersion: $(JACOCO_REPORTER_VERSION)
    downloadDirectory: '$(Pipeline.Workspace)'

- script: |
    ls -al $(Pipeline.Workspace)

- script: |
    $(CORE_DIR)/core/bin/share/runalias -j -javaagent:$(Pipeline.Workspace)/jacoco/lib/jacocoagent.jar=destfile=$(Pipeline.Workspace)/jacoco.exec -j -Djava.awt.headless=true swaf -products_config $(Pipeline.Workspace)/products_config.json -test_output_dir $(Common.TestResultsDirectory) -test_aspects $(MUNIT_TEST_ASPECTS) > test_run.log
  displayName: 'Run the script /run_tests.magik to run the munit tests of the given aspects'
  workingDirectory: '$(Pipeline.Workspace)'
  env:
    SW_MSF_STARTUP_MAGIK: '$(Build.SourcesDirectory)/scripts/run_tests.magik'
    CUSTOMER_PRD_BASE_DIR: '$(Build.SourcesDirectory)'
    SMALLWORLD_REGISTRY: '$(Build.SourcesDirectory)/smallworld_registry'

- task: PublishPipelineArtifact@1
  condition: and(succeededOrFailed(), eq(${{parameters.AZ_DEBUG}}, true))
  displayName: 'Publish test log for debugging purposes'
  inputs:
    targetPath: '$(Pipeline.Workspace)/test_run.log'
    artifact: 'test_run_log'
    publishLocation: 'pipeline'

- task: PythonScript@0
  displayName: 'Create NUnit test results from Magik test results'
  name: create_nunit_xml
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'scripts/convert_magik_xml_to_nunit_xml.py'
    arguments: '$(Common.TestResultsDirectory) $(Pipeline.Workspace)/testresult.xml'
    failOnStderr: true

- task: PublishPipelineArtifact@1
  condition: and(succeededOrFailed(), eq(${{parameters.AZ_DEBUG}}, true))
  displayName: 'Publish nunit.xml for debugging purposes'
  inputs:
    targetPath: '$(Pipeline.Workspace)/testresult.xml'
    artifact: 'testresult.xml'
    publishLocation: 'pipeline'

- script: |
    java -jar $(Pipeline.Workspace)/sw5-jacoco-reporter.jar --product-path /home/vsts/work/1/s/customer_engine_prd --product-path /home/vsts/work/1/s/customer_prd --jacoco-file  $(Pipeline.Workspace)/jacoco.exec --jacoco-xml  $(Pipeline.Workspace)/coverage_results.xml

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: $(Pipeline.Workspace)/coverage_results.xml
    #pathToSources: # string. Path to Source files. 
    #failIfCoverageEmpty: false # boolean. Fail if code coverage results are missing. Default: false

- task: PublishTestResults@2
  displayName: 'Publish MUnit test results'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(Pipeline.Workspace)/testresult.xml'
    failTaskOnFailedTests: true

- ${{ if eq(parameters.AZ_BUILD_ALL, true) }}:
  - script: echo 'Build all, so skip magik-lint'
    displayName: skip magik-lint
- ${{ elseif ne(parameters.AZ_BUILD_THIS, '{}') }}:
  - script: echo 'Build specific product, so skip magik-lint'
    displayName: skip magik-lint
- ${{ else }}:
  - task: UniversalPackages@0
    displayName: 'Download magik-lint'
    inputs:
      command: download
      vstsFeed: '$(System.TeamProject)/$(AZ_FEED)'
      vstsFeedPackage: $(MAGIK_LINT_ARTIFACT_NAME)
      vstsPackageVersion: $(MAGIK_LINT_ARTIFACT_VERSION)
      downloadDirectory: '$(Pipeline.Workspace)'

  - task: PythonScript@0
    displayName: 'Run the magik-linter'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'scripts/magik_lint.py'
      arguments: '$(Pipeline.Workspace)/changed_files.txt $(Pipeline.Workspace)/$(MAGIK_LINT_JAR) $(MAGIK_LINT_EXIT_CODE_FAILS) > $(Pipeline.Workspace)/lint_results.log'

  - task: PublishPipelineArtifact@1
    condition: and(succeededOrFailed(), eq(${{parameters.AZ_DEBUG}}, true))
    displayName: 'Publish lint-results log for debugging purposes'
    inputs:
      targetPath: '$(Pipeline.Workspace)/lint_results.log'
      artifact: 'lint_results.log'
      publishLocation: 'pipeline'

- task: PythonScript@0
  displayName: 'Zip the artifacts and upload to Artifact storage'
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'scripts/zip_and_upload.py'
    arguments: '"$(System.CollectionUri)" "$(System.TeamProject)" "$(AZ_FEED)" "$(Pipeline.Workspace)/products_config.json" $(CUSTOMER_APP_VERSION) $(Build.ArtifactStagingDirectory)'
    failOnStderr: false # because somehow something is written to Stderr even when nothing is failing....
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

