# set variables. Get the volatile one from the library group. The rest is set to point to directories for easy reading
variables:
  - group: customer-app-vars
  - name: AZ_SW_PRODUCT_TO_BUILD
    value: customer_app
  - name: CUSTOMER_ARTIFACT
    value: $(AZ_SW_PRODUCT_TO_BUILD)-$(customer_prd_VERSION).zip
  - name: REGISTRY_ARTIFACT
    value: smallworld_registry-$(customer_prd_VERSION).zip
  - name: RUN_ARTIFACT
    value: run-$(customer_prd_VERSION).zip

# Deployment job
jobs:
- deployment: Deploy_VM_with_customer_prd
  displayName: 'Deploy Customer App on VMFrank'
  pool:
    vmImage: 'Ubuntu-latest'
  environment: 
    name: 'customer_prd_Dev.VMFrank'
  strategy:
    runOnce:
      deploy:
        steps:
        # upload customer app
        - task: UniversalPackages@0
          displayName: 'Download customer app artifact'
          inputs:
            command: download
            vstsFeed: '$(AZ_FEED)'
            vstsFeedPackage: $(CUSTOMER_ARTIFACT)
            vstsPackageVersion: '*'
            downloadDirectory: '$(System.DefaultWorkingDirectory)'
        - task: UniversalPackages@0
          displayName: 'Download smallworld_registry'
          inputs:
            command: download
            vstsFeed: '$(AZ_FEED)'
            vstsFeedPackage: $(REGISTRY_ARTIFACT)
            vstsPackageVersion: '*'
            downloadDirectory: '$(System.DefaultWorkingDirectory)'
        - task: UniversalPackages@0
          displayName: 'Download run folder'
          inputs:
            command: download
            vstsFeed: '$(AZ_FEED)'
            vstsFeedPackage: $(RUN_ARTIFACT)
            vstsPackageVersion: '*'
            downloadDirectory: '$(System.DefaultWorkingDirectory)'

        - task: ExtractFiles@1
          displayName: 'Extract custom app artifact to the designated directory on the target server'
          inputs:
            archiveFilePatterns: '*.zip'
            destinationFolder: $(DEPLOY_DIR)

